name: add-pr-comment
on:
  [pull_request]
  # workflow_dispatch:
  # pull_request:
  #   types: [opened]
jobs:
  comment:
    if: contains(github.event.issue.pull_request.title, 'refactor')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log('aaaa', github.event.issue.pull_request)

            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '![Refactor Gif](https://media.giphy.com/media/mEyjlcnnKADLziMIZS/giphy-downsized.gif)'
            });
